config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # get 'contacto/:sucursal' => 'front/contact#contacto'
  get 'contacto' => 'front/contact#contacto'
  get 'trabaja-con-nosotros' => 'front/contact#work_with_us'
  post 'contacto/:sucursal' => 'front/contact#send_contact'
  post 'trabaja-con-nosotros' => 'front/contact#send_work_with_us'

  devise_for :users,
             path: 'admin/auth',
             path_names: { sign_in: 'sign_in', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  #ADMIN routes
  authenticated :user do
    get 'admin' => 'admin#home', as: :user_root
    get 'admin/home' => 'admin#home_page'
    post 'admin/numbers/update' => 'admin#numbers_update'
    post 'admin/home_slider/update' => 'admin#home_slider_update'
    post 'admin/home_promo_slider/update' => 'admin#home_promo_slider_update'
    post 'admin/home_images/update' => 'admin#home_images_update'
    post 'admin/home_texts/update' => 'admin#home_texts_update'
    resources :products, path: '/admin/products'
    resources :categories, path: '/admin/categories'
    resources :services, path: '/admin/services'
    resources :users, path: '/admin/users'
    resources :projects, path: '/admin/projects'
    resources :pages, path: '/admin/pages'
    resources :partners, path: '/admin/partners'
    resources :sliders, path: '/admin/sliders' do

    end
    resources :slider_images, path: '/admin/slider'
    resources :slider_videos, path: '/admin/slider/video'
    resources :brands, path: '/admin/brands'
    resources :menus, path: '/admin/menus'

    delete 'comment/delete/:all' => 'comments#destroy'

    get 'search' => 'welcome#search'
    get 'admin/chat' => 'admin#chat'
    get 'admin/chat/change_status' => 'admin#change_status'
    get 'admin/chat/refresh_table' => 'admin#refresh_table'
    get 'admin/chat/cancel_chat' => 'chat#cancel_chat'
    get 'admin/chat/accept_chat' => 'chat#accept_chat'

    get 'chat/room/:room' => 'chat#room'
    post 'chat/send_message' => 'chat#messages'
    post 'chat/get_messages' => 'chat#get_messages'
    post 'chat/disconnect' => 'chat#disconnect'
  end
  unauthenticated :user do
    get  'admin' => 'admin#auth'
    get  'productos/search' => 'welcome#home'
    get  'admin/products/:all' => 'admin#home'
    get  'admin/products' => 'admin#home'
    get  'admin/products/:all/edit' => 'admin#home'
    get  'admin/products/new' => 'admin#home'
    get  'admin/categories/:all' => 'admin#auth'
    get  'admin/categories' => 'admin#auth'
    get  'admin/categories/new' => 'admin#auth'
    get  'admin/categories/:all/edit' => 'admin#auth'
    get  'admin/services/:all' => 'admin#auth'
    get  'admin/services' => 'admin#auth'
    get  'admin/services/new' => 'admin#auth'
    get  'admin/services/:all/edit' => 'admin#auth'
    get  'admin/projects/:all' => 'admin#auth'
    get  'admin/projects' => 'admin#auth'
    get  'admin/projects/new' => 'admin#auth'
    get  'admin/projects/:all/edit' => 'admin#auth'
    get  'admin/menus' => 'admin#auth'
    get  'admin/menus/new' => 'admin#auth'
    get  'admin/menus/:all/edit' => 'admin#auth'

  end

  #PAGINAS INTERIORES

  post 'comment/create' => 'comments#create'
  get 'holding' => 'front/partners#holding'
  get 'proyectos-ejecutados' => 'front/projects#proyectos_ejecutados'
  get 'proyectos-ejecucion' => 'front/projects#proyectos_ejecucion'

  post 'pusher/auth' => 'pusher#auth'
  get  'chat_room' => 'chat#index'
  get 'conectar' => 'chat#conectar'
  #mostrar servicios

  #mostrar products
  get  '/productos'=> 'welcome#index'
  get 'productos/:brand/:product_url' => 'welcome#index'
  #search products
  get  'productos/:brand' => 'welcome#index'

  #mostrar proyectos
  get 'proyectos/search' => 'front/projects#search_projects'
  get 'proyectos-ejecutados/search' => 'front/projects#search_projects'
  get 'proyectos-ejecutados/:project_url' => 'front/projects#show_proyecto'
  get 'proyectos-ejecucion/:project_url' => 'front/projects#show_proyecto'
  if Rails.env.development?
    get 'upurls' => 'front/projects#update_project_urls'

  end
  get '/:page_name/' => 'front/interior_pages#interior_pages' , :except => ['contacto','trabaja-con-nosotros','/' ,'porque-videocorp' ]
  get '/:page_name/:sub_page' => 'front/interior_pages#interior_pages' , :except => ['contacto','trabaja-con-nosotros','/' ,'porque-videocorp']
end

app/models/project.rb
class Project < ActiveRecord::Base
  self.primary_key = 'id'

  def previous_project
    Project.where(["id < ? AND project_category_id = 1" , id]).order("id desc").first
  end
  def next_project
    Project.where(["id > ? AND project_category_id = 1" , id]).order("id asc").first
  end
  def previous_exec_project
    Project.where(["id < ? AND project_category_id = 2" , id]).order("id desc").first
  end
  def next_exec_project
    Project.where(["id > ? AND project_category_id = 2" , id]).order("id asc").first
  end

  paginates_per 5

  belongs_to :project_category
  has_many :images, dependent: :destroy

  has_attached_file :avatar_projects ,
                    styles: {large: "800x600" ,medium: "400x300", thumb: "200x100", icon: "100x50"},
                    default_url: "missing.png"
  has_attached_file :customer_logo ,
                    styles: {large: "800x600" ,medium: "400x300", thumb: "200x100", icon: "100x50"},
                    default_url: "logo.png"

  validates_attachment_content_type :avatar_projects, content_type: /\Aimage\/.*\Z/
end

app/controllers/front/projects_controller.rb
class Front::ProjectsController < HomeController
  def proyectos_ejecucion
    @page = Page.new
    @page.title = "Proyectos en ejecución"

    @pejecucion = 1
    add_breadcrumb "Proyectos en ejecución" , 'proyectos-ejecucion'
    if params[:category]
      @category = params[:category]
      @category = Category.find(params[:category])
    else
      @category = Category.new
      @category.id = 0
    end

    @search_id = 1
    @title = 'Proyectos'
    @projects = Project.where(project_category_id: '1').page params[:page]
    @featured_projects = Project.where(["is_featured =  1 AND project_category_id = 1"])
    @project_categories = Category.all

    render "welcome/proyectos"
  end
  def proyectos_ejecutados
    @page = Page.new
    @page.title = "Proyectos ejecutados"

    @pejecutados = 1
    add_breadcrumb "Proyectos ejecutados" , 'proyectos-ejecutados'
    if params[:category]
      @category = params[:category]
      @category = Category.find(params[:category])
    else
      @category = Category.new
      @category.id = 0
    end

    @search_id = 2
    @title = 'Proyectos'
    @projects = Project.where(project_category_id: '2').order(created_at: :desc).page params[:page]
    @featured_projects = Project.where(["is_featured =  1 AND project_category_id = 2"])
    @project_categories = Category.all

    render "welcome/proyectos"
  end
  def show_proyecto
    @project = Project.where(url: params[:project_url]).first

    @page = Page.new
    @page.title = @project.name

    @project_images = Image.where(project_id: @project.id)
    if @project.project_category_id == 1
      @pejecucion = 1
      add_breadcrumb "Proyectos en ejecución" , ' ../proyectos-ejecucion'
    else
      @pejecutados = 1
      add_breadcrumb "Proyectos ejecutados" , '../proyectos-ejecutados'
    end
    add_breadcrumb  @project.name

    render "welcome/proyecto"
  end

  # GET /projects
  def search_projects
    @page = Page.new
    @page.title = "Proyectos"

    @project_ids = Array.new()
    @project_categories = Category.all
    @search_id = params[:sid]

    if !params[:keywords].nil?
      @keywords = params[:keywords]
      @projects = Project.where("name LIKE ? OR description LIKE ?","%#{@keywords}%", "%#{@keywords}%").page params[:page]
      add_breadcrumb "Busqueda: "+@keywords
    else
      @category = Category.find(params[:category])
      @title = @category.name
      @cat_projects = Project.where("involved_areas = :category_id AND project_category_id = :project_category_id",{category_id:params[:category],project_category_id: @search_id})
      if @cat_projects != nil
        @cat_projects.each do |cp|
          @project_ids <<  cp.id
        end
      else
        @project_ids = @category.id
      end

      if @search_id == "1"
        @pejecucion = 1
        add_breadcrumb "Proyectos en ejecución" , '../proyectos-ejecucion'
      else
        @pejecutados = 1
        add_breadcrumb "Proyectos ejecutados" , '../proyectos-ejectuados'
      end
      @projects = Project.where(id: @project_ids).page params[:page]
    end
    @search_id = 2
    @content = ''

    render "welcome/proyectos"
  end
  def update_project_urls
    @projects = Project.all
    @projects.each do |p|
      @project = p
      name = @project.name.gsub(' ','-').gsub('.','')
      url = name.to_s + '-' + @project.id.to_s
      @project.url = url
      @project.save!
    end

    @products = Product.all
    @products.each do |p|
      @product = p
      name = @product.name.gsub(' ','-').gsub('.','')
      brand = Brand.find(@product.brand_id)
      url = brand.name + '/' + name.to_s + '-' + @product.id.to_s
      @product.url = url
      @product.save!
    end

    self.index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'json'
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  layout "admin_layout"
  before_action :set_path
  before_action :set_categories


  def set_categories
    @project_categories = ProjectCategory.all
  end

  def set_path
    @path = "projects"
    @section = "Proyectos"
  end
  # GET /projects
  # GET /projects.json
  def index
    if params[:search]
      s = params[:search]
      @projects = Project.where("name LIKE ?","%#{s}%").page params[:page]
    else
      if params[:project_type]
        @projects = Project.where("project_category_id = ? ",params[:project_type].to_i).page params[:page]
      else
        @projects = Project.all.page params[:page]
      end
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project_categories = ProjectCategory.all
    @project = Project.new
    @title = "Nuevo Proyecto"
    @categories = Category.all
  end

  # GET /projects/1/edit
  def edit
    @title = "Editar Proyecto"
    @project_categories = ProjectCategory.all
    @categories = Category.all
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        if params[:images]
          params[:images].each { |image|
            @project.images.create(image: image)
          }
        end
        if params[:principal_img]
          @project.images.create(image: params[:principal_img])
        end

        name = project_params[:name].gsub(' ','-').gsub('.','')
        url = name.to_s + '-' + @project.id.to_s
        @project.url = url
        @project.save!

        format.html { redirect_to @project, notice: 'El proyecto fue creado correctamente.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if params[:avatar_projects]
      render :text => params[:avatar_projects]
    end
    respond_to do |format|
      if @project.update(project_params)
        if params[:images]
          Image.where(:project_id => @project.id).destroy_all
          params[:images].each { |image|
            @project.images.create(image: image)
          }
        end

        name = project_params[:name].gsub(' ','-').gsub('.','')
        url = name.to_s + '-' + @project.id.to_s
        @project.url = url
        @project.save!

        format.html { redirect_to @project, notice: 'El proyecto fue editado correctamente' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    Image.where(:project_id => @project.id).destroy_all
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'El proyecto fue eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :date, :customer_name, :description, :avatar_projects,:principal_img, :customer_logo, :project_type, :images, :project_category_id, :is_featured, :involved_areas, :project_video,:testimonial_video,:search)
    end
end

app/helpers/front/projects_helper.rb
module Front::ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <%= form_for(@project) do |f| %>
          <div class="col-md-12 ">
            <button type="submit" class="btn btn-success pull-right" id="save_button">
              <i class="material-icons">save</i>
              Guardar</button>

          </div>
          <div class="col-md-12">
            <div class="card">
              <div class="card-header" data-background-color="blue">
                <h4 class="title"><%= @title %></h4>
                <p class="category"></p>
              </div>
              <div class="card-content">
                <% if @project.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this product from being saved:</h2>

                      <ul>
                        <% @project.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
                <div class="col-md-8">
                  <div class="col-md-12">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Titulo </label>
                      <%= f.text_field :name, class: 'form-control' %>
                      <span class="material-input"></span>
                    </div>
                  </div>
                  <!--div class="col-md-12">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Imagenes</label>
                    </div>
                    <div class="label-floating is-empty">
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </div>
                    <span class="info">
                        800x600
                      </span>
                    <hr>
                  </div-->
                  <div class="col-md-12">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Cliente </label>
                      <%= f.text_field :customer_name, class: 'form-control' %>
                      <span class="material-input"></span>
                    </div>
                  </div>
                  <!--div class="col-md-12">
                    <div class="form-group label-floating  is-empty">
                      <label class="label">Logo cliente</label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="label-floating is-empty">
                      <% if @project.customer_logo.url != nil %>
                          <div class="col-md-4">
                            <%= image_tag  @project.customer_logo.url %>
                          </div>
                      <% end %>
                      <%= f.file_field :customer_logo, id: 'customer_logo' %>
                    </div>
                  </div-->
                  <div class="col-md-6">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Tipo de proyecto</label>
                      <input type="hidden" id="selected_categories" name="project[project_category_id]" value="<%= @project.project_category_id == nil ? 3 : @project.project_category_id  %>">
                      <br>
                      <form id="check_form">
                        <% @project_categories.each do |c|  %>
                          <input type="radio" class="project_category_id" value="<%= c.id %>" id="<%= c.name %>" name="project_category_id"<%= @project.project_category_id != nil ?   @project.project_category_id == c.id ? 'checked' : '': c.id == 3 ? 'checked' : '' %>/><label for="<%= c.name %>"> <%= c.name %></label>
                          <br />
                        <% end %>
                      </form>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Fecha del proyecto</label>
                      <div class='input-group date' id=''>
                        <%= f.text_field :date, class:"form-control", placeholder:"DD/MM/AAAA (05/10/2016)"%>
                        <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                          </span>
                      </div>
                    </div>
                  </div>

                  <!--div class="col-md-12">
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="label">Video del proyecto </label>
                        <%= f.text_field :project_video, class: 'form-control', placeholder: 'URL del video', id: 'project-video' %>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="label">Video testimonial </label>
                        <%= f.text_field :testimonial_video, class: 'form-control', placeholder: 'URL del video' , id: 'testimonial-video' %>
                      </div>
                    </div>
                  </div-->
                  <div class="col-md-6">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Área relacionada</label>
                    </div>
                    <input type="hidden" name="project[involved_areas]" >
                    <form id="check_form">

                      <% @categories.each do |c| %>
                        <input type="radio" class="involved_area" value="<%= c.id %>" id="<%= c.name %>" name="involved_area" <%= @project.involved_areas.to_i == c.id.to_i ? 'checked' : '' %>/><label for="<%= c.name %>"> &nbsp;&nbsp;  <%=c.name.capitalize %></label><br />
                      <% end %>
                    </form>
                  </div>
                  <!--div class="col-md-6">
                    <div class="form-group label-flaoting is-empty">
                      <input type="checkbox" id="check_featured" value="" <%= @project.is_featured == 1 ? 'checked'  : '' %>>
                      <label for="check_featured">Proyecto destacado</label>
                      <input type="hidden" name="project[is_featured]" id="input_feat" value="<%= @project.is_featured == 1 ? '1'  :'0' %>">
                    </div>
                  </div-->
                  <div class="col-md-12">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Descripción</label>
                      <%= f.cktext_area :description,class: 'form-control', :style =>  'border: 1px solid #ccc;border-top:none' %>

                    </div>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="card">
                    <div class="card-header" data-background-color="blue">
                      <h4 class="title">Imagen Principal</h4>
                    </div>
                    <div class="card-content">
                      <div class="col-md-12">
                        <%= image_tag @project.avatar_projects.url, {class: 'thumbnail img form_img no-float center-block',id:'img_form'} %>
                        <%= f.file_field :avatar_projects, id: 'file_img' %>
                        <br>
                      </div>
                      <hr>
                      <span class="info">
                            800x600
                          </span>
                      <hr>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <input type="hidden" name="project[status]" value="1">
      <% end %>
    </div>

  </div>
</div>

<script type="text/javascript" charset="utf-8">
  document.getElementById("file_img").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
      // get loaded data and render thumbnail.
      document.getElementById("img_form").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
  };
  $(document).ready(function(){

      var data = <%= @project.project_category_id.nil? ? 3 : @project.project_category_id %>
          $('input[name="project[project_category_id]"]').val(data);

      $('.project_category_id').change(function(){
        $('input[name="project[project_category_id]"]').val($(this).val());
      });

    $('#check_featured').change(function(){
      var c = this.checked ? '1' : '0';
      $('#input_feat').val(c);
    });



    var data = <%= @project.project_category_id.nil? ? '' : @project.project_category_id %>
        $('input[name="project[project_category_id]"]').val(data);

    $('.involved_area').change(function(){
      $('input[name="project[involved_areas]"]').val($(this).val());
    });

    $('#project-video').focusout(function(){
      var str = $('#project-video').val();
      var res = str.replace("watch?v=", "embed/");
      $('#project-video').val(res);
    });
    $('#testimonial-video').focusout(function(){
      var str = $('#testimonial-video').val();
      var res = str.replace("watch?v=", "embed/");
      $('#testimonial-video').val(res);
    });
  });
</script>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <%= render "layouts/admin/search" %>
      <div class="col-md-12">
        <div class="card">
          <div class="option_buttons">
            <%= link_to  new_project_path, class: 'white-text pull-right', :'title'=>'Nuevo Proyecto' do %>
                <i class="material-icons">edit</i>
                Nuevo Proyecto
                <div class="ripple-container"></div>
            <% end %>
            <div class="col-md-6 white-text pull-right" >
              <a href="/admin/projects?project_type=1" class="filter-button">Proyectos en Ejecución</a>
                &nbsp;/&nbsp;
              <a href="/admin/projects?project_type=2" class="filter-button">Proyectos Ejecutados</a>
                &nbsp;/&nbsp;
              <a href="/admin/projects?project_type=3" class="filter-button">Sin Categoría</a>
                &nbsp;/&nbsp;
              <a href="/admin/projects" class="filter-button">Todo</a>
            </div>
          </div>
          <div class="card-header" data-background-color="blue">
            <h4 class="title">Listado de Proyectos</h4>
          </div>
          <div class="card-content">
            <div id="typography">
              <% if @projects.count < 1 %>
                  <div class="col-md-6 alert alert-warning center-block no-float alert-with-icon">
                    <i data-notify="icon" class="material-icons">info_outline</i>
                    <span class="message">
                      <b> Oops! - </b> No hay proyectos para mostrar,
                      <%= link_to 'haga click aquí para crear uno nuevo', new_project_path %></span>
                  </div>
              <% else %>
                  <div class="title">
                  </div>
                  <div class="row">
                    <table class="table">
                      <thead class="text-primary">
                      <tr>
                        <th>Título</th>
                        <th>Tipo</th>
                        <th>Destacado</th>
                        <th>Imagen</th>
                        <th>Opciones</th>
                      </tr></thead>
                      <tbody>
                      <% @projects.each do |project| %>
                          <tr>
                            <td><%= project.name %></td>
                            <td><%= project.project_category.name %></td>
                            <td><%= project.is_featured == 1 ? 'Si' : 'No' %></td>
                            <td><%= image_tag project.avatar_projects.url(:icon), class:'thumbnails list-icon' %></td>
                            <td><%= link_to 'Ver', project ,{class: 'btn btn-success'} %>
                              <%= link_to 'Editar', edit_project_path(project) ,{class: 'btn btn-info'} %>
                              <%= link_to 'Eliminar', project, method: :delete, data: { confirm: '¿Esta seguro?' }, class: 'btn btn-danger' %></td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                  <%= paginate @projects %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 center-block no-float">
        <div class="card card-profile">
          <div class="card-avatar">
            <%= image_tag @project.avatar_projects.url, {class: 'thumbnail form_img'} %>
          </div>
          <div class="content" style="padding: 5px 2em;">
            <p class="card-content" >
              <span>Producto <strong> <%= @project.name %></strong></span>
            <hr>
            <span>Tipo <strong> <%= @project.project_category.name %></strong></span>

            <hr>
            <span>Descripción <strong> <%= @project.description.to_s[0,55]  %> ...</strong></span>
            <hr>
            <%= link_to 'EDITAR', edit_project_path(@project),{class: 'btn btn-info'} %> |
            <%= link_to 'VOLVER', '/admin/projects',{class: 'btn btn-alert'} %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>