config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # get 'contacto/:sucursal' => 'front/contact#contacto'
  get 'contacto' => 'front/contact#contacto'
  get 'trabaja-con-nosotros' => 'front/contact#work_with_us'
  post 'contacto/:sucursal' => 'front/contact#send_contact'
  post 'trabaja-con-nosotros' => 'front/contact#send_work_with_us'

  devise_for :users,
             path: 'admin/auth',
             path_names: { sign_in: 'sign_in', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  #ADMIN routes
  authenticated :user do
    get 'admin' => 'admin#home', as: :user_root
    get 'admin/home' => 'admin#home_page'
    post 'admin/numbers/update' => 'admin#numbers_update'
    post 'admin/home_slider/update' => 'admin#home_slider_update'
    post 'admin/home_promo_slider/update' => 'admin#home_promo_slider_update'
    post 'admin/home_images/update' => 'admin#home_images_update'
    post 'admin/home_texts/update' => 'admin#home_texts_update'
    resources :products, path: '/admin/products'
    resources :categories, path: '/admin/categories'
    resources :services, path: '/admin/services'
    resources :users, path: '/admin/users'
    resources :projects, path: '/admin/projects'
    resources :pages, path: '/admin/pages'
    resources :partners, path: '/admin/partners'
    resources :sliders, path: '/admin/sliders' do

    end
    resources :slider_images, path: '/admin/slider'
    resources :slider_videos, path: '/admin/slider/video'
    resources :brands, path: '/admin/brands'
    resources :menus, path: '/admin/menus'

    delete 'comment/delete/:all' => 'comments#destroy'

    get 'search' => 'welcome#search'
    get 'admin/chat' => 'admin#chat'
    get 'admin/chat/change_status' => 'admin#change_status'
    get 'admin/chat/refresh_table' => 'admin#refresh_table'
    get 'admin/chat/cancel_chat' => 'chat#cancel_chat'
    get 'admin/chat/accept_chat' => 'chat#accept_chat'

    get 'chat/room/:room' => 'chat#room'
    post 'chat/send_message' => 'chat#messages'
    post 'chat/get_messages' => 'chat#get_messages'
    post 'chat/disconnect' => 'chat#disconnect'
  end
  unauthenticated :user do
    get  'admin' => 'admin#auth'
    get  'productos/search' => 'welcome#home'
    get  'admin/products/:all' => 'admin#home'
    get  'admin/products' => 'admin#home'
    get  'admin/products/:all/edit' => 'admin#home'
    get  'admin/products/new' => 'admin#home'
    get  'admin/categories/:all' => 'admin#auth'
    get  'admin/categories' => 'admin#auth'
    get  'admin/categories/new' => 'admin#auth'
    get  'admin/categories/:all/edit' => 'admin#auth'
    get  'admin/services/:all' => 'admin#auth'
    get  'admin/services' => 'admin#auth'
    get  'admin/services/new' => 'admin#auth'
    get  'admin/services/:all/edit' => 'admin#auth'
    get  'admin/projects/:all' => 'admin#auth'
    get  'admin/projects' => 'admin#auth'
    get  'admin/projects/new' => 'admin#auth'
    get  'admin/projects/:all/edit' => 'admin#auth'
    get  'admin/menus' => 'admin#auth'
    get  'admin/menus/new' => 'admin#auth'
    get  'admin/menus/:all/edit' => 'admin#auth'

  end

  #PAGINAS INTERIORES

  post 'comment/create' => 'comments#create'
  get 'holding' => 'front/partners#holding'
  get 'proyectos-ejecutados' => 'front/projects#proyectos_ejecutados'
  get 'proyectos-ejecucion' => 'front/projects#proyectos_ejecucion'

  post 'pusher/auth' => 'pusher#auth'
  get  'chat_room' => 'chat#index'
  get 'conectar' => 'chat#conectar'
  #mostrar servicios

  #mostrar products
  get  '/productos'=> 'welcome#index'
  get 'productos/:brand/:product_url' => 'welcome#index'
  #search products
  get  'productos/:brand' => 'welcome#index'

  #mostrar proyectos
  get 'proyectos/search' => 'front/projects#search_projects'
  get 'proyectos-ejecutados/search' => 'front/projects#search_projects'
  get 'proyectos-ejecutados/:project_url' => 'front/projects#show_proyecto'
  get 'proyectos-ejecucion/:project_url' => 'front/projects#show_proyecto'
  if Rails.env.development?
    get 'upurls' => 'front/projects#update_project_urls'

  end
  get '/:page_name/' => 'front/interior_pages#interior_pages' , :except => ['contacto','trabaja-con-nosotros','/' ,'porque-videocorp' ]
  get '/:page_name/:sub_page' => 'front/interior_pages#interior_pages' , :except => ['contacto','trabaja-con-nosotros','/' ,'porque-videocorp']
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  self.primary_key = 'id'
  paginates_per 10
  has_many :products

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  layout "admin_layout"
  before_action :set_path

  def set_path
    @path = "brands"
    @section = "Marcas"
  end

  # GET /brands
  # GET /brands.json
  def index
    if params[:search]
      s = params[:search]
      @brands = Brand.where("name LIKE ?","%#{s}%").page params[:page]
    else
      @brands = Brand.all.page params[:page]
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/views/brands/_form.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <%= form_for(@brand) do |f| %>
          <div class="col-md-12 ">
            <button type="submit" class="btn btn-success pull-right" id="save_button">
              <i class="material-icons">save</i>
              Guardar</button>

          </div>
          <div class="col-md-12">
            <div class="card">
              <div class="card-header" data-background-color="blue">
                <h4 class="title"><%= @title %></h4>
                <p class="category"></p>
              </div>
              <div class="card-content">
                <% if @brand.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

                      <ul>
                        <% @brand.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
                <div class="row">
                  <div class="col-md-12">
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="label">Nombre </label>
                        <%= f.text_field :name, class: 'form-control' %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/brands/edit.html.erb
<%= render 'form' %>

app/views/brands/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <%= render "layouts/admin/search" %>
      <div class="col-md-12">
        <div class="card">
          <div class="option_buttons">
            <%= link_to  new_brand_path, class: 'white-text pull-right', :'title'=>'Nueva Marca' do %>
                <i class="material-icons">edit</i>
                Nueva Marca
                <div class="ripple-container"></div>
            <% end %>
          </div>
          <div class="card-header" data-background-color="blue">
            <h4 class="title">Listado de Marcas</h4>
          </div>
          <div class="card-content">
            <div id="typography">
              <% if @brands.count < 1 %>
                  <div class="col-md-6 alert alert-warning center-block no-float alert-with-icon">
                    <i data-notify="icon" class="material-icons">info_outline</i>
                    <span class="message">
                      <b> Oops! - </b> No hay marcas para mostrar,
                      <%= link_to 'haga click aquí para crear una nuevo', new_brand_path %></span>
                  </div>
              <% else %>
                  <div class="title">
                  </div>
                  <div class="row">
                    <table class="table">
                      <thead class="text-primary">
                      <tr>
                        <th>Nombre</th>
                        <th>Opciones</th>
                      </tr></thead>
                      <tbody>
                      <% @brands.each do |brand| %>
                          <tr>
                            <td><%= brand.name %></td>
                            <td><%= link_to 'Ver', brand ,{class: 'btn btn-success'} %>
                              <%= link_to 'Editar', edit_brand_path(brand) ,{class: 'btn btn-info'} %>
                              <%= link_to 'Eliminar', brand, method: :delete, data: { confirm: '¿Esta seguro?' }, class: 'btn btn-danger' %></td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                  <%= paginate @brands %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/brands/new.html.erb
<%= render 'form' %>

app/views/brands/show.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 center-block no-float">
        <div class="card card-profile">

          <div class="content" style="padding: 5px 2em;">
            <p class="card-content" >
              <span>Nombre: <strong> <%= @brand.name %></strong></span>
            <hr>
            <%= link_to 'EDITAR', edit_brand_path(@brand),{class: 'btn btn-info'} %> |
            <%= link_to 'VOLVER', '/admin/brands',{class: 'btn btn-alert'} %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>