config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # get 'contacto/:sucursal' => 'front/contact#contacto'
  get 'contacto' => 'front/contact#contacto'
  get 'trabaja-con-nosotros' => 'front/contact#work_with_us'
  post 'contacto/:sucursal' => 'front/contact#send_contact'
  post 'trabaja-con-nosotros' => 'front/contact#send_work_with_us'

  devise_for :users,
             path: 'admin/auth',
             path_names: { sign_in: 'sign_in', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  #ADMIN routes
  authenticated :user do
    get 'admin' => 'admin#home', as: :user_root
    get 'admin/home' => 'admin#home_page'
    post 'admin/numbers/update' => 'admin#numbers_update'
    post 'admin/home_slider/update' => 'admin#home_slider_update'
    post 'admin/home_promo_slider/update' => 'admin#home_promo_slider_update'
    post 'admin/home_images/update' => 'admin#home_images_update'
    post 'admin/home_texts/update' => 'admin#home_texts_update'
    resources :products, path: '/admin/products'
    resources :categories, path: '/admin/categories'
    resources :services, path: '/admin/services'
    resources :users, path: '/admin/users'
    resources :projects, path: '/admin/projects'
    resources :pages, path: '/admin/pages'
    resources :partners, path: '/admin/partners'
    resources :sliders, path: '/admin/sliders' do

    end
    resources :slider_images, path: '/admin/slider'
    resources :slider_videos, path: '/admin/slider/video'
    resources :brands, path: '/admin/brands'
    resources :menus, path: '/admin/menus'

    delete 'comment/delete/:all' => 'comments#destroy'

    get 'search' => 'welcome#search'
    get 'admin/chat' => 'admin#chat'
    get 'admin/chat/change_status' => 'admin#change_status'
    get 'admin/chat/refresh_table' => 'admin#refresh_table'
    get 'admin/chat/cancel_chat' => 'chat#cancel_chat'
    get 'admin/chat/accept_chat' => 'chat#accept_chat'

    get 'chat/room/:room' => 'chat#room'
    post 'chat/send_message' => 'chat#messages'
    post 'chat/get_messages' => 'chat#get_messages'
    post 'chat/disconnect' => 'chat#disconnect'
  end
  unauthenticated :user do
    get  'admin' => 'admin#auth'
    get  'productos/search' => 'welcome#home'
    get  'admin/products/:all' => 'admin#home'
    get  'admin/products' => 'admin#home'
    get  'admin/products/:all/edit' => 'admin#home'
    get  'admin/products/new' => 'admin#home'
    get  'admin/categories/:all' => 'admin#auth'
    get  'admin/categories' => 'admin#auth'
    get  'admin/categories/new' => 'admin#auth'
    get  'admin/categories/:all/edit' => 'admin#auth'
    get  'admin/services/:all' => 'admin#auth'
    get  'admin/services' => 'admin#auth'
    get  'admin/services/new' => 'admin#auth'
    get  'admin/services/:all/edit' => 'admin#auth'
    get  'admin/projects/:all' => 'admin#auth'
    get  'admin/projects' => 'admin#auth'
    get  'admin/projects/new' => 'admin#auth'
    get  'admin/projects/:all/edit' => 'admin#auth'
    get  'admin/menus' => 'admin#auth'
    get  'admin/menus/new' => 'admin#auth'
    get  'admin/menus/:all/edit' => 'admin#auth'

  end

  #PAGINAS INTERIORES

  post 'comment/create' => 'comments#create'
  get 'holding' => 'front/partners#holding'
  get 'proyectos-ejecutados' => 'front/projects#proyectos_ejecutados'
  get 'proyectos-ejecucion' => 'front/projects#proyectos_ejecucion'

  post 'pusher/auth' => 'pusher#auth'
  get  'chat_room' => 'chat#index'
  get 'conectar' => 'chat#conectar'
  #mostrar servicios

  #mostrar products
  get  '/productos'=> 'welcome#index'
  get 'productos/:brand/:product_url' => 'welcome#index'
  #search products
  get  'productos/:brand' => 'welcome#index'

  #mostrar proyectos
  get 'proyectos/search' => 'front/projects#search_projects'
  get 'proyectos-ejecutados/search' => 'front/projects#search_projects'
  get 'proyectos-ejecutados/:project_url' => 'front/projects#show_proyecto'
  get 'proyectos-ejecucion/:project_url' => 'front/projects#show_proyecto'
  if Rails.env.development?
    get 'upurls' => 'front/projects#update_project_urls'

  end
  get '/:page_name/' => 'front/interior_pages#interior_pages' , :except => ['contacto','trabaja-con-nosotros','/' ,'porque-videocorp' ]
  get '/:page_name/:sub_page' => 'front/interior_pages#interior_pages' , :except => ['contacto','trabaja-con-nosotros','/' ,'porque-videocorp']
end

app/models/category.rb
class Category < ActiveRecord::Base
  self.primary_key = 'id'

  paginates_per 6

  has_attached_file :image , styles: {principal: "286x258", thumb: "100x100"}, default_url: "missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  validates :slug, presence: true

  def childrens(id)
    @childrens = Category.where(category_id:  id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout "admin_layout"
  before_action :set_path

  def set_path
    @path = "categories"
    @section = "Categorías"
  end
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where(["id != 5 AND id != 6"]).page params[:page]
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @title = 'Crear Nueva Categoría'
    @action = "new"
    @category = Category.new
    @categories = Category.all
  end

  # GET /categories/1/edit
  def edit
    @title = 'Editar Categoría'
    @categories = Category.all
    @action = "edit"
  end

  # POST /categories
  # POST /categories.json
  def create
    if !Category.where(slug: category_params['slug']).present?
      @category = Category.new(category_params)
      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'La categoría ha sido creada correctamente.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    else
     redirect_to :back, alert: 'Categoría con url: '+category_params['slug']+' ya existe'
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'La categoría ha sido editada correctamente.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'La categoría ha sido eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_id, :desciption, :slug, :image, :icon)
    end
end

app/views/categories/_form.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <%= form_for(@category) do |f| %>
          <div class="col-md-12 ">
            <button type="submit" class="btn btn-success pull-right">
              <i class="material-icons">save</i>
              Guardar</button>

          </div>
          <div class="col-md-8">
            <div class="card">
              <div class="card-header" data-background-color="blue">
                <h4 class="title"><%= @title %></h4>
                <p class="category"></p>
              </div>
              <div class="card-content">
                <% if @category.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

                      <ul>
                        <% @category.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Nombre </label>
                      <%= f.text_field :name, class: 'form-control' %>
                      <span class="material-input"></span>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group label-floating is-empty">
                      <label class="label">URL </label>
                      <%= f.text_field :slug, class: 'form-control' %>
                      <span class="material-input"></span>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group label-floating is-empty">
                      <% if @category != nil %>
                        <%  if @category.id != nil  and @category.id > 4 %>
                        <label class="label">Categoría Padre</label>
                        <input type="hidden" id="selected_categories"  name="category[category_id]" value="">
                        <select id="select_cat"  class="selectpicker"data-live-search="true" required>
                          <% @categories.each do |c|  %>
                              <% if c.category_id == 0 %>
                                  <option data-tokens="<%= c.name%>" value="<%= c.id %>"><%= c.name%></option>
                                  <% @childrens = c.childrens(c.id) %>
                                  <% if @childrens.count > 0  %>
                                      <% @childrens.each do |child|  %>
                                          <option data-tokens="<%= child.name%>"  value="<%= child.id %>" style="border-top:1px dashed #eee;margin-left:5%"><%= child.name%></option>
                                      <% end %>
                                  <% end %>
                              <% end %>
                          <% end %>
                        </select>
                        <% else %>
                          <% if @action != "edit" %>
                              <label class="label">Categoría Padre</label>
                              <input type="hidden" id="selected_categories"  name="category[category_id]" value="">
                              <select id="select_cat"  class="selectpicker"data-live-search="true" required>
                                <% @categories.each do |c|  %>
                                    <% if c.category_id == 0 %>
                                        <option data-tokens="<%= c.name%>" value="<%= c.id %>"><%= c.name%></option>
                                        <% @childrens = c.childrens(c.id) %>
                                        <% if @childrens.count > 0  %>
                                            <% @childrens.each do |child|  %>
                                                <option data-tokens="<%= child.name%>"  value="<%= child.id %>" style="border-top:1px dashed #eee;margin-left:5%"><%= child.name%></option>
                                            <% end %>
                                        <% end %>
                                    <% end %>
                                <% end %>
                              </select>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group label-floating is-empty">
                      <label class="label">Descripcion</label>
                      <%= f.text_area :description, class: 'form-control', rows: '10' %>
                      <span class="material-input"></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-header" data-background-color="blue">
                <h4 class="title">Imagen</h4>
              </div>
              <div class="card-content">
                <div class="col-md-12">
                  <%= image_tag @category.image.url, {class: 'thumbnail img form_img no-float center-block',id:'img_form'} %>
                  <%= f.file_field :image, id: 'file_img' %>
                  <br>
                </div>
              </div>

            </div>
          </div>
          <input type="hidden" name="category[status]" value="1">
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  document.getElementById("file_img").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
      // get loaded data and render thumbnail.
      document.getElementById("img_form").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
  };
</script>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="option_buttons">
            <%= link_to  new_category_path, class: 'white-text pull-right', :'title'=>'Nueva Categoría' do %>
                <i class="material-icons">edit</i>
                Nuevo Categoría
                <div class="ripple-container"></div>
            <% end %>
          </div>
          <div class="card-header" data-background-color="blue">
            <h4 class="title">Listado de Categorías</h4>
          </div>
          <div class="card-content">
            <div id="typography">
              <% if @categories.count < 1 %>
                  <div class="col-md-6 alert alert-warning center-block no-float alert-with-icon">
                    <i data-notify="icon" class="material-icons">info_outline</i>
                    <span class="message">
                      <b> Oops! - </b> No hay categorías para mostrar,
                      <%= link_to 'haga click aquí para crear uno nuevo', new_category_path %></span>
                  </div>
              <% else %>
                  <div class="title">
                  </div>
                  <div class="row">
                    <table class="table">
                      <thead class="text-primary">
                      <tr>
                        <th>Nombre</th>
                        <th>slug</th>
                        <th>Imagen</th>
                        <th>Estado</th>
                        <th>Opciones</th>
                      </tr></thead>
                      <tbody>
                      <% @categories.each do |category| %>
                          <tr>
                            <td><%= category.name %></td>
                            <td><%= category.slug %></td>
                            <td><%= image_tag category.image.url(:thumb), class:'thumbnails list-icon' %></td>
                            <td><%= category.status %></td>
                            <td><%= link_to 'Ver', category ,{class: 'btn btn-success'} %>
                              <%= link_to 'Editar', edit_category_path(category) ,{class: 'btn btn-info'} %>
                              <% if category.id > 4%>
                              <%= link_to 'Eliminar', category, method: :delete, data: { confirm: '¿Esta seguro?' }, class: 'btn btn-danger' %>
                              <% end%>
                            </td>
                          </tr></tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                  <%= paginate @categories %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 center-block no-float">
        <div class="card card-profile">
          <div class="card-avatar">
            <%= image_tag @category.image.url, {class: 'thumbnail form_img avatar-thumb'} %>
          </div>
          <div class="content" style="padding: 5px 2em;">
            <p class="card-content">
              <span>Categoría <strong> <%= @category.name %></strong></span>
            <hr>
            <span>Slug <strong> <%= @category.slug %></strong></span>
            <hr>
            <%= link_to 'EDITAR', edit_category_path(@category),{class: 'btn btn-info'} %> |
            <%= link_to 'VOLVER', '/admin/categories',{class: 'btn btn-alert'} %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>